export const Icon = {
    settings: "settings",
    chart: "chart",
    calendar: "calendar",
    check: "check",
    chip: "chip",
    compass: "compass",
    database: "database",
    flag: "flag",
    home: "home",
    info: "info",
    link: "link",
    lock: "lock",
    messages: "messages",
    notification: "notification",
    payment: "payment",
    power: "power",
    receipt: "receipt",
    shield: "shield",
    star: "star",
    tune: "tune",
    videoRecorder: "videoRecorder",
    wallet: "wallet",
    warning: "warning",
    headphone: "headphone",
    send: "send",
    pipelines: "pipelines",
    person: "person",
    category: "category",
    contact: "contact",
    clipboardIcon: "clipboardIcon",
  } as const;

export type Icon = keyof typeof Icon;